-- MySQL Script generated by MySQL Workbench
-- Min 30 Jun 2019 09:42:14  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_koperasi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_koperasi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_koperasi` DEFAULT CHARACTER SET latin1 ;
USE `db_koperasi` ;

-- -----------------------------------------------------
-- Table `db_koperasi`.`dompet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`dompet` (
  `id_dompet` VARCHAR(11) NOT NULL,
  `saldo` INT(30) NOT NULL DEFAULT '0',
  `id_akun` VARCHAR(11) NOT NULL,
  `point` INT(30) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_dompet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_room` (
  `id_room` INT(11) NOT NULL,
  `room` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_room`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_akuns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_akuns` (
  `id_akun` VARCHAR(11) NOT NULL,
  `username` VARCHAR(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `birth` VARCHAR(10) NULL DEFAULT NULL,
  `id_room` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(50) NOT NULL,
  `nim` VARCHAR(11) NULL DEFAULT NULL,
  `no_hp` VARCHAR(15) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `image` TEXT NULL DEFAULT NULL,
  `level` INT(1) NULL DEFAULT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `last_update` DATETIME NULL DEFAULT NULL,
  `id_dompet` VARCHAR(11) NULL DEFAULT NULL,
  `motto` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_akun`),
  INDEX `dompet akun_idx` (`id_dompet` ASC),
  INDEX `kamar akun_idx` (`id_room` ASC),
  CONSTRAINT `dompet akun`
    FOREIGN KEY (`id_dompet`)
    REFERENCES `db_koperasi`.`dompet` (`id_dompet`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `kamar akun`
    FOREIGN KEY (`id_room`)
    REFERENCES `db_koperasi`.`tb_room` (`id_room`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_kategori` (
  `id_kategori` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_kategori` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_kategori`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_produk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_produk` (
  `id_produk` VARCHAR(11) NOT NULL,
  `nama_produk` VARCHAR(30) NULL DEFAULT NULL,
  `harga_modal` INT(100) NOT NULL,
  `harga_jual` INT(100) NULL DEFAULT NULL,
  `id_kategori` INT(11) NULL DEFAULT NULL,
  `stok_produk` INT(11) NULL DEFAULT NULL,
  `deskripsi_produk` TEXT NULL DEFAULT NULL,
  `gambar_produk` VARCHAR(50) NULL DEFAULT 'default.jpg',
  `terjual` INT(11) NULL DEFAULT '0',
  `id_dompet` VARCHAR(11) NULL,
  PRIMARY KEY (`id_produk`),
  INDEX `kategori produk_idx` (`id_kategori` ASC),
  CONSTRAINT `kategori produk`
    FOREIGN KEY (`id_kategori`)
    REFERENCES `db_koperasi`.`tb_kategori` (`id_kategori`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_status_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_status_order` (
  `id_status_order` INT(1) NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status_order`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_metode_bayar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_metode_bayar` (
  `id_metode_bayar` INT(1) NOT NULL,
  `metode_bayar` VARCHAR(45) NULL,
  PRIMARY KEY (`id_metode_bayar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_order` (
  `id_order` INT(15) NOT NULL,
  `id_akun` VARCHAR(11) NULL DEFAULT NULL,
  `waktu_order` DATETIME NULL DEFAULT NULL,
  `id_status` INT(1) NULL DEFAULT '0',
  `id_metode_bayar` INT(1) NULL,
  PRIMARY KEY (`id_order`),
  INDEX `status orderan_idx` (`id_status` ASC),
  INDEX `akun yg order_idx` (`id_akun` ASC),
  INDEX `metode pembayaran_idx` (`id_metode_bayar` ASC),
  CONSTRAINT `status orderan`
    FOREIGN KEY (`id_status`)
    REFERENCES `db_koperasi`.`tb_status_order` (`id_status_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `akun yg order`
    FOREIGN KEY (`id_akun`)
    REFERENCES `db_koperasi`.`tb_akuns` (`id_akun`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `metode pembayaran`
    FOREIGN KEY (`id_metode_bayar`)
    REFERENCES `db_koperasi`.`tb_metode_bayar` (`id_metode_bayar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_koperasi`.`tb_detail_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_koperasi`.`tb_detail_order` (
  `id_detail_order` INT(11) NOT NULL AUTO_INCREMENT,
  `id_order` INT(11) NULL DEFAULT NULL,
  `id_produk` VARCHAR(11) NULL DEFAULT NULL,
  `kuantitas` INT(100) NULL DEFAULT NULL,
  `total_harga` INT(100) NULL DEFAULT NULL,
  `total_harga2` INT(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detail_order`),
  INDEX `produk order_idx` (`id_produk` ASC),
  INDEX `id_ordernya_idx` (`id_order` ASC),
  CONSTRAINT `produk order`
    FOREIGN KEY (`id_produk`)
    REFERENCES `db_koperasi`.`tb_produk` (`harga_modal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_ordernya`
    FOREIGN KEY (`id_order`)
    REFERENCES `db_koperasi`.`tb_order` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1111
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
